"""Frontend API Contract changes

Revision ID: 232d735c0766
Revises: 0006_suggestion_reviews
Create Date: 2026-08-26 08:55:42.453959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232d735c0766'
down_revision: Union[str, None] = '0006_suggestion_reviews'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_approved_by'), 'broadcasts', ['approved_by'], unique=False)
    op.create_index(op.f('ix_broadcasts_complaint_id'), 'broadcasts', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_broadcasts_department_id'), 'broadcasts', ['department_id'], unique=False)
    op.create_table('complaint_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_comments_author_id'), 'complaint_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_complaint_comments_complaint_id'), 'complaint_comments', ['complaint_id'], unique=False)
    op.drop_index('ix_complaint_embeddings_embedding', table_name='complaint_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_complaint_relations_source_complaint_id'), 'complaint_relations', ['source_complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_relations_target_complaint_id'), 'complaint_relations', ['target_complaint_id'], unique=False)
    op.add_column('complaints', sa.Column('ticket_number', sa.String(length=20), nullable=False))
    op.add_column('complaints', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('complaints', sa.Column('solution', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('solution_cost', sa.String(length=120), nullable=True))
    op.add_column('complaints', sa.Column('solution_time', sa.String(length=120), nullable=True))
    op.add_column('complaints', sa.Column('solution_reliability', sa.String(length=120), nullable=True))
    op.add_column('complaints', sa.Column('admin_decision', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_complaints_ticket_number'), 'complaints', ['ticket_number'], unique=True)
    op.drop_constraint('student_profiles_prn_number_key', 'student_profiles', type_='unique')
    op.drop_constraint('student_profiles_user_id_key', 'student_profiles', type_='unique')
    op.create_index(op.f('ix_student_profiles_prn_number'), 'student_profiles', ['prn_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.add_column('users', sa.Column('username', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_prn_number'), table_name='student_profiles')
    op.create_unique_constraint('student_profiles_user_id_key', 'student_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('student_profiles_prn_number_key', 'student_profiles', ['prn_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_complaints_ticket_number'), table_name='complaints')
    op.drop_column('complaints', 'admin_decision')
    op.drop_column('complaints', 'solution_reliability')
    op.drop_column('complaints', 'solution_time')
    op.drop_column('complaints', 'solution_cost')
    op.drop_column('complaints', 'solution')
    op.drop_column('complaints', 'tags')
    op.drop_column('complaints', 'ticket_number')
    op.drop_index(op.f('ix_complaint_relations_target_complaint_id'), table_name='complaint_relations')
    op.drop_index(op.f('ix_complaint_relations_source_complaint_id'), table_name='complaint_relations')
    op.create_index('ix_complaint_embeddings_embedding', 'complaint_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_complaint_comments_complaint_id'), table_name='complaint_comments')
    op.drop_index(op.f('ix_complaint_comments_author_id'), table_name='complaint_comments')
    op.drop_table('complaint_comments')
    op.drop_index(op.f('ix_broadcasts_department_id'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_complaint_id'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_approved_by'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
